###
POST http://localhost:8000/api/v1/user/registration
Content-Type: application/json

###
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "yubaraj.100mgr@gmail.com",
    "password": "1"
}


###
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json

{
    "transSactionName": "jkdlsajflka",
    "date": "01/01/2020",
    "type": "Income",
    "amount": 1000
}
